name: mmimdb
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - torchvision
  - pytorch-cuda=11.7
  - tensorboard
  - Pillow
  - scikit-learn
  - numpy
  - tqdm
  - matplotlib
  - pip
  - pip:
    - pytorch-pretrained-bert
